name: ViaBackwards
version: ${project.version}
main: nl.matsv.viabackwards.ViaBackwards
description: Allows 1.9.x on a 1.10 Spigot server

authors: [Matsv]
website: https://matsv.nl

load: STARTUP
depend: [ViaVersion]
